### PR TITLE
add Generating visualizations from Cauldron

### PR DESCRIPTION
**Pull request by GeorgLink**
Documenting the steps necessary in Cauldron to generate visualizations for CHAOSS Community Health reports.

The goal is to allow anyone to do these steps.

### CODE REVIEW

**Comment by jaskiratsingh2000** [comment]
Thank you very much @GeorgLink for the contribution.

**Comment by ElizabethN** [comment]
@GeorgLink Just a couple of questions: 
1) I'm not sure where someone can find more information about using/installing Cauldron. You mentioned _Information 1_ in the commit but I don't know what that is or where it links to?
2) We don't really have any information about Cauldron in the Community Handbook - should we? It might be confusing for a new person to understand the relationship between Cauldron and CHAOSS.

Thanks again for writing this out!

**Comment by GeorgLink** [comment]
@ElizabethN 

1a) we should add a link to cauldron.io; no installation required?
1b) `information 1` refers to the first piece of information that Vinod shared.
2) hmm... I'd be hesitant to add a Cauldron page because Cauldron is not a CHAOSS project; maybe add a block of information to the Cauldron stuff as a down-stream project?

I'll open a new PR to fix (1)

**Comment by ElizabethN** [comment]
@GeorgLink 
1) Yes, that's perfect! And explicitly calling out that nothing needs to be installed is a big selling point I think. 
2) 👍  got it.
3) I think even if we say that it's not a CHAOSS project but built on GL that would be enough. Or maybe I'm completely overthinking it :laughing:

**Comment by GeorgLink** [comment]
Thanks @ElizabethN 

See #9 for my response

**Pull request merged**
