### PR TITLE
Delete chaosscon.md

### LINKED ISSUE #10: Delete second chaosscon.md file ?
The repository has two `chaosscon.md` files:

1. https://github.com/chaoss/community-handbook/blob/master/chaosscon.md
2. https://github.com/chaoss/community-handbook/blob/master/community-initiatives/chaosscon.md

The [Handbook Page](https://app.gitbook.com/@chaoss-project/s/community-handbook/community-initiatives/chaosscon) seems to match file # 2.

Can we safely delete file # 1?

### PR DESCRIPTION
**Pull request by GeorgLink**
Delete outdated file not part of handbook; probably result of sync error.

fixes #10

### CODE REVIEW

**Review by jaskiratsingh2000 — COMMENTED** [review]
Seems like you are on a wrong file as it says you are on # 2 link which is fine but we have to delete the # 1. Correct me if I am wrong. Thanks!

**Comment by GeorgLink** [comment]
hmmm... I thought this is the file that's outdated. The other file has emojis like we see on the handbook. 

What do I need to do?

**Comment by jaskiratsingh2000** [comment]
Yes, so the second file is the updated one as it has emojis on it whereas
the first one is outdated.
You should delete the first one.

**Comment by GeorgLink** [comment]
I double checked the PR against your description:

The "first" file is in the root folder and that's the one this PR is deleting.
The "second" file is in a sub-directory and that's the one we keep because it's in use.

If this is still wrong, could you then please create a correct PR so I can see what you mean?

**Comment by jaskiratsingh2000** [comment]
Okay maybe due to wrong naming it might have caused the issue. Its fine,
Please go ahead. Thanks!

**Pull request merged**
