### PR TITLE
Season of docs Proposal

### PR DESCRIPTION
**Pull request by pratik2315**
This PR contains the tasklist for the GSoD project [Website and Metric Release](https://github.com/chaoss/community/issues/354)

### CODE REVIEW

**Comment by germonprez** [comment]
Hi @pratik2315. Thanks for the PR. I'd like to ask that you break these down as per each file you are proposing to change. Also, please remember to apply your DCO to your PRs.

**Comment by klumb** [comment]
@pratik2315, the task for the website and metrics release documentation does not require a PR to the community handbook at this time. It just requires that you fork the repo and make the requested changes there. 

When we review the proposals we will look at your proposal and your forked repo.

**Comment by pratik2315** [comment]
Okay @germonprez I will take care of it from the next time! 

Sorry for the PR @klumb🙏 I have referenced the fork in my GSoD proposal already! I will close this PR right away. Thanks again!

**Comment by klumb** [comment]
@pratik2315 - no worries and keep up the good work.

**Comment by pratik2315** [comment]
> @pratik2315 - no worries and keep up the good work.

👍🙌

**Pull request closed without merging**
