### PR TITLE
Added WG repo template

### PR DESCRIPTION
**Pull request by ritik-malik**
Hi @GeorgLink,

As discussed, I've added the WG repo template to the community handbook,
also I've appended it with the text from [`file-name-convention.md`](https://github.com/chaoss/wg-common/blob/master/template-folder/file-name-convention.md)
(Next I would be adding this `file-name-convention.md` to the chaoss/metrics repo)

please let me know if any changes are required

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thank you.

Can you add the file-name-convention.md text to this document? Let's keep this together and avoid multiple files.

**Comment by GeorgLink** [comment]
There is some language that we could change now or later (not a requirement to get this merged). 

For example "Move any metric that was not released or is under community review into an issue with a google doc" is an action required to bring a repo into the new structure -- it is not describing the structure itself. Such action can be converted into a statement about the repo structure.

**Comment by ritik-malik** [comment]
I've already appended this document with the text from file-name-convention.md in the end (does it needs its own separate sub-heading?)

As for the language change, I expected that as a sub problem and can be looked upon in a separate PR maybe? WDYT?

For now I've converted that action to a statement

**Review by GeorgLink — APPROVED** [review]
Thanks @ritik-malik

**Comment by GeorgLink** [comment]
I agree!

**Pull request merged**
